### ISSUE TITLE
You either suck at scamming or your assets are being used for scamming 

### ISSUE THREAD

**Issue by MattStar45** [KeepWannabe/daily-panel-assets#1]
![8748BFD4-D741-4A73-A12E-E9A27ED4B238](https://user-images.githubusercontent.com/56000169/97486333-ae1a8e80-1931-11eb-9f24-46706c848734.jpeg)
lol

**Comment by KeepWannabe** [comment]
Hello MattStar45 !

wow i dont expect this, can you tell med what scam it is ? chase ? thanks before to tell me :) ill delete that assets

**Comment by MattStar45** [comment]
Hello, yes you’re chase images are being used for scamming. Sorry this came across as a aggressive, but its irritating to see scammers do this type of stuff and the only lead I had for the origin was your image 😅

**Comment by KeepWannabe** [comment]
Hi matt thanks again for your help, no problem i appreciate it :) thanks for info !
